//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinhDuongVirtualTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE
    {
        public int idType { get; set; }
        public string Place_Name { get; set; }
    }
}
